[package]
name = "random-strategy"
version = "0.1.0"
edition = "2021"

[dependencies]
wit-bindgen = "0.46.0"

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
package = "pig-pen:player"

[package.metadata.component.dependencies]
